### ISSUE TITLE
Top-right buttons are confusing

### ISSUE THREAD

**Issue by C0rn3j** [lll2yu/sddm-lain-wired-theme#1]
What are they for? One is apparently for shutdown. Would it be possible to at least have a label on hover?

**Comment by lll2yu** [comment]
@C0rn3j added tooltip in 09b1bbc6d9160e410c5aaec731cbad4bdb9b46a8 ,can you test that?
![2019-01-23_00 30 34](https://user-images.githubusercontent.com/20357133/51558948-b31df480-1ea6-11e9-8e03-0411c04a956b.png)

**Comment by C0rn3j** [comment]
Looks great! 
It'd be perfect if hovering over the other label destroyed other currently present labels (so you don't get two overlapping labels at the same time), but that's just nitpicking

**Comment by lll2yu** [comment]
> hovering over the other label destroyed other currently present labels

I'll try to fix it soon.
