### ISSUE TITLE
Audio plays through the wrong output

### ISSUE THREAD

**Issue by C0rn3j** [lll2yu/sddm-lain-wired-theme#2]
The music plays through my headset, not speakers. The DE (KDE) outputs to the correct one (everything else but speakers is set to disabled in pavucontrol).

Not sure if this isn't more of a SDDM issue rather than the theme itself?

Arch Linux, installed the package through AUR.

**Comment by lll2yu** [comment]
Does the audio play through speakers when headset is disconnected?
