### ISSUE TITLE
Cloning doesn't supply the proper text for certain Strings

### ISSUE THREAD

**Issue by sojudev** [lll2yu/sddm-lain-wired-theme#3]
User ID:
Password: 
Login
Reboot
Shutdown

The Strings above in the .qml files are all just blocks (similar to []). I'm curious if anybody knows what the fix to this is? I'd like to use the same font that shows up here on github. Thanks!

**Comment by lll2yu** [comment]
@kaneru-soju Hi, did this issue get resolved?

**Comment by swindlesmccoop** [comment]
This issue has not been resolved. I get the same error, whether I clone it or download from AUR using yay. Possibly a missing font issue?

**Comment by swindlesmccoop** [comment]
Actually, I figured out the issue purely by accident.
`sudo pacman -S adobe-source-han-sans-jp-fonts otf-ipafont`
`yay -S ttf-monapo`
`sudo pacman -S ibus ibus-anthy`

Then, append the following to ~/.xprofile
```
export GTK_IM_MODULE='ibus'
export QT_IM_MODULE='ibus'
export XMODIFIERS=@im='ibus'
ibus-daemon -drx

**Comment by indigomarxist** [comment]
if anyone is still having the same issue, i fixed it by simply replacing the "special" text with `p l a i n t e x t l i k e t h i s`.
keysearch `/text` in **RebootToolTip.qml**, S**hutdownToolTip.qml**, and **Main.qml**.
